basePath: /
definitions:
  dto.CreateCommentRequest:
    properties:
      content:
        example: Это комментарий к задаче
        maxLength: 1000
        minLength: 1
        type: string
    required:
    - content
    type: object
  dto.CreatePermissionRequest:
    properties:
      email:
        example: example@example.com
        type: string
      role:
        example: viewer/editor
        type: string
    type: object
  dto.CreateProjectRequest:
    properties:
      description:
        example: описание проекта
        type: string
      name:
        example: Написать API
        type: string
    type: object
  dto.CreateTaskRequest:
    properties:
      description:
        example: описание задачи
        type: string
      due_date:
        example: "2025-11-20T13:37:27+00:00"
        type: string
      priority:
        example: low/medium/high
        type: string
      status:
        example: todo/in-progress/done
        type: string
      title:
        example: написать функцию
        minLength: 1
        type: string
    required:
    - title
    type: object
  dto.ErrorResponse:
    properties:
      error:
        example: Произошла ошибка
        type: string
      success:
        example: false
        type: boolean
    type: object
  dto.LoginRequest:
    properties:
      email:
        example: example@example.com
        type: string
      password_hash:
        example: "123456"
        minLength: 6
        type: string
    required:
    - email
    - password_hash
    type: object
  dto.RegisterRequest:
    properties:
      email:
        example: example@example.com
        type: string
      name:
        example: vasiliy1234
        minLength: 1
        type: string
      password_hash:
        example: "123456"
        minLength: 6
        type: string
    required:
    - email
    - name
    - password_hash
    type: object
  dto.SuccessResponse:
    properties:
      data: {}
      message:
        example: Операция выполнена успешно
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: Support Team
  description: API для управления задачами, проектами и комментариями
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: SaaS
  version: "1.0"
paths:
  /api/comments/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет комментарий по ID. Требуются права редактора или владельца
        проекта.
      parameters:
      - description: ID комментария
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Комментарий удален
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Недостаточно прав
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Комментарий не найден
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить комментарий
      tags:
      - comments
  /me:
    get:
      consumes:
      - application/json
      description: Возвращает данные авторизованного пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователя
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "401":
          description: Не авторизован
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить информацию о текущем пользователе
      tags:
      - users
  /projects:
    get:
      consumes:
      - application/json
      description: Возвращает список проектов авторизованного пользователя и их описание.
        Требуются права просмотра проекта.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
      security:
      - BearerAuth: []
      summary: Получить список проектов
      tags:
      - project
    post:
      consumes:
      - application/json
      description: Создаёт новую запись в таблице проектов.
      parameters:
      - description: название и описание проекта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать проект
      tags:
      - project
  /projects/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет запись из таблицы проектов. Требуются права редактора проекта.
      parameters:
      - description: id проекта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить проект
      tags:
      - project
    get:
      consumes:
      - application/json
      description: Возвращает проект и его описание. Требуются права просмотра проекта.
      parameters:
      - description: id проекта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить конкретный проект
      tags:
      - project
    patch:
      consumes:
      - application/json
      description: Изменяет данные проекта на данные из тела запроса. Требуются права
        редактора проекта.
      parameters:
      - description: id проекта
        in: path
        name: id
        required: true
        type: integer
      - description: название и описание проекта для редактирования
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Изменить проект
      tags:
      - project
  /projects/{id}/share:
    post:
      consumes:
      - application/json
      description: Создаёт новую запись в таблице прав. Требуются права владельца
        проекта.
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      - description: Email и роль для выдачи роли
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePermissionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Выдать права другому пользователю
      tags:
      - permission
  /projects/{id}/share/{user_id}:
    delete:
      consumes:
      - application/json
      description: Удаляет запись в таблице прав. Требуются права владельца проекта.
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить права у пользователя
      tags:
      - permission
  /projects/{id}/tasks:
    get:
      consumes:
      - application/json
      description: Возвращает все задачи проекта. Требуются права просмотра проекта.
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить задачи проекта
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Создаёт новую запись в таблице задач. Требуются права редактора
        проекта.
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      - description: Название, описание, статус, приоритет и дата завершения задачи
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать задачу
      tags:
      - task
  /signin:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя и возвращает JWT токен в cookie.
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Вход в систему
      tags:
      - auth
  /signout:
    post:
      consumes:
      - application/json
      description: Разлогинивает пользователя и удаляет куки авторизации.
      produces:
      - application/json
      responses:
        "200":
          description: успешный логаут
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "404":
          description: пользователь не найден
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Выход из системы
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя в системе.
      parameters:
      - description: Данные для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь зарегистрирован
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Неверный запрос или пользователь уже существует
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет запись в таблице задач. Требуются права редактора проекта.
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить
      tags:
      - task
    patch:
      consumes:
      - application/json
      description: Изменяет запись в таблице задач. Требуются права редактора проекта.
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      - description: Название, описание, статус, приоритет и дата завершения задачи
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Изменить задачу
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Возвращает одну конкретную задачу. Требуются права просмотра проекта.
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить задачу
      tags:
      - task
  /tasks/{id}/comments:
    get:
      consumes:
      - application/json
      description: Возвращает все комментарии для указанной задачи. Требуются права
        просмотра проекта.
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить комментарии задачи
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Создает новый комментарий для указанной задачи. Требуются права
        редактора или владельца проекта.
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      - description: Данные комментария
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать комментарий к задаче
      tags:
      - comments
securityDefinitions:
  BearerAuth:
    description: Введите "Bearer {token}" (без кавычек)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
